"""
filter.py — Candidate profile filtering.

Rules are loaded from data/filter_config.json, which is generated by
`manage.py apply-prefs` from the plain-English USER_PREFS.md file.
Edit USER_PREFS.md and re-run apply-prefs to change filtering behaviour.
"""

import json
import logging
import os
import re
from pathlib import Path

logger = logging.getLogger(__name__)

_CONFIG_FILE = Path(__file__).resolve().parent.parent / "data" / "filter_config.json"

# When evaluator.py is running it decides inclusion by reading the posting, so
# this module steps back to a cheap coarse gate: geography, plus titles that are
# obviously wrong. Keeping the title-INCLUDE gate on would defeat the brief's
# core instruction that titles are the worst available signal here, and would
# drop the postings the evaluator exists to catch (a role that never says
# "Chief of Staff" but is one). Title EXCLUDES stay on either way: they are
# cheap, high-precision, and keep evaluator cost down.
_EVALUATOR_ENABLED = os.getenv("EVALUATOR_ENABLED", "1").strip().lower() not in ("0", "false", "no")

# Floor set of hourly / entry-level titles, applied ONLY when the evaluator is
# enabled and the title-include gate is therefore off.
#
# Why this is in code rather than filter_config.json: the generated config
# mirrors USER_PREFS, and the current brief's hard excludes are all senior-level
# mismatches (banking VP, preconstruction). It says nothing about hourly roles,
# so apply-prefs emits no pattern for them — correctly, since they were never
# the problem when a seniority keyword was required. With that requirement
# lifted, every hourly posting from a hospital or theme park careers page would
# otherwise reach the model. These are pure cost: the evaluator rejects all of
# them, so paying to have it read them buys nothing.
_ENTRY_LEVEL_FLOOR: tuple[str, ...] = (
    r"\bcashier\b", r"\bbarista\b", r"\bbartender\b", r"\bserver\b", r"\bwaits?(taff|er|ress)\b",
    r"\bhost(ess)?\b", r"\bbusser\b", r"\bdishwasher\b", r"\bline cook\b", r"\bprep cook\b",
    r"\bhousekeep(er|ing)\b", r"\bcustodian\b", r"\bjanitor(ial)?\b", r"\bgroundskeeper\b",
    r"\blifeguard\b", r"\bvalet\b", r"\bbell(hop|man)\b", r"\bconcierge\b",
    r"\bsales associate\b", r"\bretail associate\b", r"\bstock(er|room)\b", r"\bwarehouse associate\b",
    r"\bcrew member\b", r"\bteam member\b", r"\battendant\b", r"\bcast member\b",
    r"\bdriver\b", r"\btechnician\b", r"\bmechanic\b", r"\bmaintenance worker\b",
    r"\breceptionist\b", r"\bdata entry\b", r"\bscheduler\b",
    r"\bnurse\b", r"\brn\b", r"\bcna\b", r"\bmedical assistant\b", r"\bphlebotom",
    r"\b(intern|internship|apprentice|trainee)\b", r"\bentry.level\b", r"\bpart.time\b",
    r"\bseasonal\b", r"\bhourly\b", r"\bassistant\s+(manager|supervisor)\b",
)


def _load_config() -> dict:
    try:
        with open(_CONFIG_FILE, "r", encoding="utf-8") as fh:
            return json.load(fh)
    except FileNotFoundError:
        logger.warning(
            "filter_config.json not found — using empty rules. "
            "Run: py -3.11 src/manage.py apply-prefs"
        )
        return {}
    except json.JSONDecodeError as exc:
        logger.error("filter_config.json is malformed: %s — no items will be filtered out.", exc)
        return {}


# Load once at module import; the pipeline process is long-running so this
# stays current for the lifetime of one scheduler run (fine for our use case).
_cfg = _load_config()

TITLE_INCLUDE_PATTERNS: list[str]      = _cfg.get("title_include_patterns", [])
TITLE_EXCLUDE_PATTERNS: list[str]      = _cfg.get("title_exclude_patterns", [])
DESCRIPTION_EXCLUDE_TERMS: list[str]   = _cfg.get("description_exclude_terms", [])
DESCRIPTION_EXCLUDE_THRESHOLD: int     = _cfg.get("description_exclude_threshold", 3)
GEOGRAPHY_INCLUDE_TERMS: list[str]     = _cfg.get("geography_include_terms", [])
REMOTE_TERMS: list[str]                = _cfg.get("remote_terms", [])
GEOGRAPHY_EXEMPT_CATEGORIES: set[str]  = set(_cfg.get("geography_exempt_categories", []))


def _matches_any(text: str, patterns: list[str]) -> bool:
    lower = text.lower()
    return any(re.search(p, lower) for p in patterns)


def _cybersec_description_hit_count(text: str) -> int:
    lower = text.lower()
    return sum(1 for term in DESCRIPTION_EXCLUDE_TERMS if term in lower)


_SHORT_TERM_LEN = 3  # terms this short get word-boundary matching instead of substring


def _term_matches(text: str, term: str) -> bool:
    """Match term in text. Short terms (<=3 chars) use word boundaries so
    'fl' doesn't match 'flexible' / 'flow' / 'Flagstaff' and 'nc' doesn't
    match 'nautical'. Longer terms use substring so 'orlando' matches
    'orlando, fl' and 'orlando metro' alike.
    """
    if len(term) <= _SHORT_TERM_LEN:
        return re.search(rf"\b{re.escape(term)}\b", text) is not None
    return term in text


# A title carrying no real word — "R10230535-2", "Req 88231" — tells us
# nothing, and is the case the snippet fallback exists to rescue.
_REAL_WORD_RE = re.compile(r"[A-Za-z]{4,}")


def _title_is_uninformative(title: str) -> bool:
    """True when a title is a bare requisition code rather than a role name."""
    words = _REAL_WORD_RE.findall(title)
    return len(words) < 2


def _is_geography_match(
    location: str,
    title: str = "",
    snippet: str = "",
    category: str = "jobs",
) -> bool:
    """Return True if the item appears to be in the target area or is remote.

    Matching is scoped to `location` and `title`. The description is
    deliberately NOT searched: it mentions a city or the word "remote" in
    passing on almost every posting ("our Florida office", "remote work
    options available"), which would make this function return True for
    everything and silently disable geography filtering. The snippet is
    consulted only when there is no location at all — the case it was meant
    to cover.

    The "no location → treat as remote" fallback applies ONLY to jobs,
    where many ATS feeds legitimately omit the location field on remote
    roles. For news articles, no-location defaults to False — otherwise
    every global PR Newswire item with no location field passes through
    and the digest turns into a firehose of irrelevant press releases.
    """
    has_location = bool(location.strip())
    combined = " ".join([location, title] if has_location else [title, snippet]).lower()

    if any(_term_matches(combined, term) for term in REMOTE_TERMS):
        return True
    if any(_term_matches(combined, term) for term in GEOGRAPHY_INCLUDE_TERMS):
        return True
    # Jobs: no location listed → treat as potentially remote (err toward inclusion).
    # News / other: no location AND no geography mention → drop.
    if category == "jobs" and not has_location:
        return True
    return False


def apply_profile_filter(results: list, sources: list | None = None) -> list:
    """
    Filter a list of ScrapeResult objects against the candidate profile.
    Returns only items that pass all rules.

    `sources` is the source list from sources.json — if provided, items whose
    source carries `remote_only_source: true` are exempted from geography
    filtering. Every item from a remote-only source is by definition remote
    work, so its company HQ location is irrelevant.
    """
    from scraper import ScrapeResult  # local import to avoid circular

    # If no include patterns configured, pass everything through with a warning
    if not TITLE_INCLUDE_PATTERNS and not TITLE_EXCLUDE_PATTERNS:
        logger.warning(
            "filter_config.json has no patterns — passing all %d items through unfiltered. "
            "Run: py -3.11 src/manage.py apply-prefs",
            len(results),
        )
        return results

    # Build the remote-only source lookup
    remote_only_ids: set[str] = set()
    if sources:
        remote_only_ids = {
            s["id"] for s in sources if s.get("remote_only_source") is True
        }

    accepted: list[ScrapeResult] = []
    entry_level_dropped = 0
    for item in results:
        title     = item.title    or ""
        location  = item.location or ""
        snippet   = item.snippet  or ""
        category  = item.category or "jobs"
        seniority = getattr(item, "seniority", "") or ""
        # Prefer the full description for the saturation check; fall back to
        # the snippet for sources that only ever produce one.
        body      = getattr(item, "description", "") or snippet
        is_remote_only = item.source_id in remote_only_ids

        # ── 1. Jobs: the role level must show a seniority keyword ────────────
        # Checked against the title and the structured `seniority` field the
        # posting page gives us ("Mid-Senior level").
        #
        # The description is deliberately NOT a general fallback. The include
        # list holds common words — "senior", "lead", "operations", "partner",
        # "strategy" — that appear in nearly every job description, so matching
        # against it would admit essentially everything and turn this gate into
        # a no-op. It is consulted only for the case it was written for: a
        # title that is a bare requisition code and says nothing at all.
        if category == "jobs" and TITLE_INCLUDE_PATTERNS and not _EVALUATOR_ENABLED:
            level_text = f"{title} {seniority}"
            if _title_is_uninformative(title):
                level_text += f" {snippet}"
            if not _matches_any(level_text, TITLE_INCLUDE_PATTERNS):
                logger.debug("EXCLUDED (no seniority keyword): %s", title)
                continue

        # ── 2. Title-level exclusion ──────────────────────────────────────────
        if TITLE_EXCLUDE_PATTERNS and _matches_any(title, TITLE_EXCLUDE_PATTERNS):
            logger.debug("EXCLUDED (excluded title): %s", title)
            continue

        # ── 2b. Entry-level floor (evaluator mode only) ──────────────────────
        # With the include gate off, this is the only thing standing between a
        # theme-park careers page and a model call per hourly posting.
        if category == "jobs" and _EVALUATOR_ENABLED and _matches_any(title, _ENTRY_LEVEL_FLOOR):
            entry_level_dropped += 1
            logger.debug("EXCLUDED (entry-level floor): %s", title)
            continue

        # ── 3. Description saturation exclusion ───────────────────────────────
        # Skipped while the evaluator runs. These terms are all information
        # security, and the brief says infosec roles are diverted to the
        # Section 6 watchlist, NOT dropped. Killing them here would leave the
        # watchlist permanently empty, because nothing downstream would ever
        # see a security posting to route.
        if DESCRIPTION_EXCLUDE_TERMS and not _EVALUATOR_ENABLED:
            hits = _cybersec_description_hit_count(body)
            if hits >= DESCRIPTION_EXCLUDE_THRESHOLD:
                logger.debug("EXCLUDED (description saturation, %d hits): %s", hits, title)
                continue

        # ── 4. Geography (exempt categories AND remote-only sources pass through) ─
        if category not in GEOGRAPHY_EXEMPT_CATEGORIES and GEOGRAPHY_INCLUDE_TERMS:
            if is_remote_only:
                logger.debug(
                    "PASS (remote-only source bypasses geography): %s [src=%s]",
                    title, item.source_id,
                )
            elif not _is_geography_match(location, title, snippet, category):
                logger.debug("EXCLUDED (geography): %s | loc=%s", title, location)
                continue

        accepted.append(item)

    logger.info(
        "Filter: %d in → %d accepted (%.0f%% pass rate)",
        len(results),
        len(accepted),
        100 * len(accepted) / len(results) if results else 0,
    )
    if entry_level_dropped:
        logger.info("Filter: %d entry-level/hourly titles dropped before scoring.",
                    entry_level_dropped)
    return accepted
