"""
filter.py — Candidate profile filtering.

Rules are loaded from data/filter_config.json, which is generated by
`manage.py apply-prefs` from the plain-English USER_PREFS.md file.
Edit USER_PREFS.md and re-run apply-prefs to change filtering behaviour.
"""

import json
import logging
import re
from pathlib import Path

logger = logging.getLogger(__name__)

_CONFIG_FILE = Path(__file__).resolve().parent.parent / "data" / "filter_config.json"


def _load_config() -> dict:
    try:
        with open(_CONFIG_FILE, "r", encoding="utf-8") as fh:
            return json.load(fh)
    except FileNotFoundError:
        logger.warning(
            "filter_config.json not found — using empty rules. "
            "Run: py -3.11 src/manage.py apply-prefs"
        )
        return {}
    except json.JSONDecodeError as exc:
        logger.error("filter_config.json is malformed: %s — no items will be filtered out.", exc)
        return {}


# Load once at module import; the pipeline process is long-running so this
# stays current for the lifetime of one scheduler run (fine for our use case).
_cfg = _load_config()

TITLE_INCLUDE_PATTERNS: list[str]      = _cfg.get("title_include_patterns", [])
TITLE_EXCLUDE_PATTERNS: list[str]      = _cfg.get("title_exclude_patterns", [])
DESCRIPTION_EXCLUDE_TERMS: list[str]   = _cfg.get("description_exclude_terms", [])
DESCRIPTION_EXCLUDE_THRESHOLD: int     = _cfg.get("description_exclude_threshold", 3)
GEOGRAPHY_INCLUDE_TERMS: list[str]     = _cfg.get("geography_include_terms", [])
REMOTE_TERMS: list[str]                = _cfg.get("remote_terms", [])
GEOGRAPHY_EXEMPT_CATEGORIES: set[str]  = set(_cfg.get("geography_exempt_categories", []))


def _matches_any(text: str, patterns: list[str]) -> bool:
    lower = text.lower()
    return any(re.search(p, lower) for p in patterns)


def _cybersec_description_hit_count(text: str) -> int:
    lower = text.lower()
    return sum(1 for term in DESCRIPTION_EXCLUDE_TERMS if term in lower)


def _is_geography_match(location: str, title: str = "", snippet: str = "") -> bool:
    """Return True if the item appears to be in the target area or is remote."""
    combined = " ".join([location, title, snippet]).lower()
    if any(term in combined for term in REMOTE_TERMS):
        return True
    if any(term in combined for term in GEOGRAPHY_INCLUDE_TERMS):
        return True
    # No location listed → treat as potentially remote
    if not location.strip():
        return True
    return False


def apply_profile_filter(results: list) -> list:
    """
    Filter a list of ScrapeResult objects against the candidate profile.
    Returns only items that pass all rules.
    """
    from scraper import ScrapeResult  # local import to avoid circular

    # If no include patterns configured, pass everything through with a warning
    if not TITLE_INCLUDE_PATTERNS and not TITLE_EXCLUDE_PATTERNS:
        logger.warning(
            "filter_config.json has no patterns — passing all %d items through unfiltered. "
            "Run: py -3.11 src/manage.py apply-prefs",
            len(results),
        )
        return results

    accepted: list[ScrapeResult] = []
    for item in results:
        title    = item.title    or ""
        location = item.location or ""
        snippet  = item.snippet  or ""
        category = item.category or "jobs"

        # ── 1. Jobs: title inclusion check ───────────────────────────────────
        if category == "jobs" and TITLE_INCLUDE_PATTERNS:
            if not _matches_any(title, TITLE_INCLUDE_PATTERNS):
                logger.debug("EXCLUDED (no seniority keyword): %s", title)
                continue

        # ── 2. Title-level exclusion ──────────────────────────────────────────
        if TITLE_EXCLUDE_PATTERNS and _matches_any(title, TITLE_EXCLUDE_PATTERNS):
            logger.debug("EXCLUDED (excluded title): %s", title)
            continue

        # ── 3. Description saturation exclusion ───────────────────────────────
        if DESCRIPTION_EXCLUDE_TERMS:
            hits = _cybersec_description_hit_count(snippet)
            if hits >= DESCRIPTION_EXCLUDE_THRESHOLD:
                logger.debug("EXCLUDED (description saturation, %d hits): %s", hits, title)
                continue

        # ── 4. Geography (exempt categories pass through) ─────────────────────
        if category not in GEOGRAPHY_EXEMPT_CATEGORIES and GEOGRAPHY_INCLUDE_TERMS:
            if not _is_geography_match(location, title, snippet):
                logger.debug("EXCLUDED (geography): %s | loc=%s", title, location)
                continue

        accepted.append(item)

    logger.info(
        "Filter: %d in → %d accepted (%.0f%% pass rate)",
        len(results),
        len(accepted),
        100 * len(accepted) / len(results) if results else 0,
    )
    return accepted
